### ISSUE TITLE
The wiringpi utility is depreciated in Raspbian 11

### ISSUE THREAD

**Issue by stinkerton18** [akuker/SuperUPS#5]
Raspberry Pi Version: 3B
RaSCSI Board: Fullspec, v2.3
SuperUPS Version: 1.0 pre-release

OS Release:
```
console@centris-pi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

Following the install instructions, the first step/prerequisite package install fails on Raspbian 11: Bullseye with the following errors:
```console@centris-pi:~ $ sudo apt-get install -y wiringpi python-smbus python-pip python3-setuptools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-smbus is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

Package wiringpi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'wiringpi' has no installation candidate
E: Package 'python-smbus' has no installation candidate
E: Package 'python-pip' has no installation candidate
```

**Comment by stinkerton18** [comment]
In searching, I found this article: https://raspberrypi.stackexchange.com/questions/133251/wiringpi-is-missing-from-bullseye-how-do-i-install-it
According to the article, pigpio is the better option anyways and I see the setup instructions for it in the SETUP doc, This might just be a doc clean-up bug.

**Comment by akuker** [comment]
Could you take a look at pull request https://github.com/akuker/SuperUPS/pull/8 ? I think this addresses your concern.

The new version shouldn't use wiring pi.

**Comment by stinkerton18** [comment]
Can confirm, pull request #8 removed the wiring pi and pigpiod needs
