### ISSUE TITLE
upscontrol.py script is not Python3 compliant

### ISSUE THREAD

**Issue by stinkerton18** [akuker/SuperUPS#7]
Raspberry Pi Version: 3B
RaSCSI Board: Fullspec, v2.3
SuperUPS Version: 1.0 pre-release

OS Release:
```
console@centris-pi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

The upscontrol.py script is using the older Python2-based print statements. I have corrected this for Python3 and can create a merge request with the updated (or renamed for python3) upscontrol.py script.

**Comment by akuker** [comment]
I've made significant updates to the python code that is on a branch. I haven't merged it to main yet :-(

I think you actually want to look at https://github.com/akuker/SuperUPS/blob/host_controller/host_monitor/upsdaemon.py

**Comment by akuker** [comment]
Could you take a look at pull request #8 ? I think this addresses your concern.

**Comment by stinkerton18** [comment]
Yes indeed. Since there's a different script, I don't see a reason to publish the minor changes to make it python3 compliant in this repo.
